#config:
  #dockerfile: .woloxci/Dockerfile
  #project_name: wolox-lab-dotnet

#services:
  #- postgres

steps:
  build:
    - echo hello

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
